[package]
name = "commander"
version = "0.1.0"
authors = ["Jack Greenberg <theProgrammerJack@gmail.com>"]
edition = "2018"

[dependencies]
wpilib = "0.4.0"
wpilib-sys = "0.4.0"

[package.metadata.frc]
team-number = 639
target-dir = "./target"
